CC = g++
PFLAGS = -Wall -Wextra -g -pedantic -O2
MFLAGS = -fsanitize=address
SRCDIR = ./src/
SOURCES = $(shell find ./src/*.cpp) # Find all cpp files
OBJECTS = $(patsubst $(SRCDIR)%.cpp, %.o, $(SOURCES)) # Replace all cpp files with .o and remove path

all: $(OBJECTS)

compile: $(OBJECTS)
	$(CC) $(PFLAGS) -o rybakki1 $(OBJECTS) -lncurses

run:
	./rybakki1

clean:
	rm -rf rybakki1 *.o

doc:

# Macro to apply to all compilable object files:
%.o: $(SRCDIR)%.cpp
	$(CC) $(PFLAGS) -c $< -lncurses

# Automaticallly generated by g++ -MM *.cpp >> Makefile:

CBonus.o: $(SRCDIR)CBonus.cpp $(SRCDIR)CEntity.h $(SRCDIR)helpers.h
CBot.o: $(SRCDIR)CBot.cpp $(SRCDIR)CPlayer.h $(SRCDIR)CEntity.h $(SRCDIR)helpers.h
CEntity.o: $(SRCDIR)CEntity.cpp $(SRCDIR)CEntity.h $(SRCDIR)helpers.h
CExplosion.o: $(SRCDIR)CExplosion.cpp $(SRCDIR)CEntity.h $(SRCDIR)helpers.h $(SRCDIR)CPlayer.h
CHuman.o: $(SRCDIR)CHuman.cpp $(SRCDIR)CPlayer.h $(SRCDIR)CEntity.h $(SRCDIR)helpers.h
CObject.o: $(SRCDIR)CObject.cpp $(SRCDIR)CEntity.h $(SRCDIR)helpers.h $(SRCDIR)CPlayer.h
CPlayer.o: $(SRCDIR)CPlayer.cpp $(SRCDIR)CPlayer.h $(SRCDIR)CEntity.h $(SRCDIR)helpers.h
CStats.o: $(SRCDIR)CStats.cpp $(SRCDIR)CStats.h $(SRCDIR)CPlayer.h $(SRCDIR)CEntity.h $(SRCDIR)helpers.h
game.o: $(SRCDIR)game.cpp $(SRCDIR)game.h $(SRCDIR)CEntity.h $(SRCDIR)helpers.h $(SRCDIR)CPlayer.h $(SRCDIR)map.h $(SRCDIR)CStats.h
helpers.o: $(SRCDIR)helpers.cpp $(SRCDIR)helpers.h $(SRCDIR)CEntity.h $(SRCDIR)CPlayer.h
main.o: $(SRCDIR)main.cpp $(SRCDIR)menu.h $(SRCDIR)game.h $(SRCDIR)CEntity.h $(SRCDIR)helpers.h $(SRCDIR)CPlayer.h $(SRCDIR)map.h $(SRCDIR)CStats.h
map.o: $(SRCDIR)map.cpp $(SRCDIR)map.h $(SRCDIR)CEntity.h $(SRCDIR)helpers.h $(SRCDIR)CPlayer.h
menu.o: $(SRCDIR)menu.cpp $(SRCDIR)menu.h
